package Core.LSU
import chisel3._
import chisel3.util._

class FromWmbCe extends Bundle{
  val addr = UInt(40.W)
  val atomic = Bool()
  val bkpta_data = Bool()
  val bkptb_data = Bool()
  val bytes_vld = UInt(16.W)
  val bytes_vld_full = Bool()
  val create_wmb_data_req = Bool()
  val create_wmb_dp_req = Bool()
  val create_wmb_gateclk_en = Bool()
  val create_wmb_req = Bool()
  val data128 = UInt(128.W)
  val data_vld = UInt(4.W)
  val dcache_inst = Bool()
  val fence_mode = UInt(4.W)
  val hit_sq_pop_dcache_line = Bool()
  val icc = Bool()
  val iid = UInt(7.W)
  val inst_flush = Bool()
  val inst_mode = UInt(2.W)
  val inst_size = UInt(3.W)
  val inst_type = UInt(2.W)
  val merge_data_addr_hit = Bool()
  val merge_data_stall = Bool()
  val merge_en = Bool()
  val merge_ptr = Vec(LSUConfig.WMB_ENTRY, Bool())
  val merge_wmb_req = Bool()
  val merge_wmb_wait_not_vld_req = Bool()
  val page_buf = Bool()
  val page_ca = Bool()
  val page_sec = Bool()
  val page_share = Bool()
  val page_so = Bool()
  val page_wa = Bool()
  val priv_mode = UInt(2.W)
  val read_dp_req = Bool()
  val same_dcache_line = Vec(LSUConfig.WMB_ENTRY, Bool())
  val sc_wb_vld = Bool()
  val spec_fail = Bool()
  val sync_fence = Bool()
  val update_dcache_dirty = Bool()
  val update_dcache_share = Bool()
  val update_dcache_valid = Bool()
  val update_dcache_way = Bool()
  val vld = Bool()
  val vstart_vld = Bool()
  val wb_cmplt_success = Bool()
  val wb_data_success = Bool()
  val write_biu_dp_req = Bool()
  val write_imme = Bool()
}

class Wmb {

}
